version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: event_attendance_nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./frontend/build:/usr/share/nginx/html
    networks:
      - internal_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: event_attendance_backend
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - SUPERADMIN_USERNAME=${SUPERADMIN_USERNAME}
      - SUPERADMIN_PASSWORD=${SUPERADMIN_PASSWORD}
      - IP_ADDRESS=${IP_ADDRESS}
    depends_on:
      - postgres
    networks:
      - internal_network

  postgres:
    image: postgres:13
    container_name: event_attendance_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal_network

volumes:
  postgres_data:

networks:
  internal_network:
    driver: bridge