version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: event_attendance_db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/data
      - ./db/init_actual.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: